spring:
  security:
    oauth2.client:
      registration:
        google:
          clientId: 250367849554-p8043nvjop13nvgjp4c6re5qjcdqj1ou.apps.googleusercontent.com
          clientSecret: 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
          scope:
            - email
            - profile
        naver:
          client-id: PZYVhA2vsSBeEKhw0f0Y
          client-secret: ZOqyVtdWjc
          scope:
            - name
            - email
            - profile_image
          client-name: Naver # 클라이언트 네임은 구글 페이스북도 대문자로 시작하더라.
          authorization-grant-type: authorization_code
          redirect-uri: http://localhost:8080/login/oauth2/code/naver
        kakao:
          clientId: 82662a6dc7085a2a3ef6a3f789996fa5
          clientSecret: 4uF4s8dqUzViXuaNPiqj3I6tix27w2Jv
          clientAuthenticationMethod: post
          authorizationGrantType: authorization_code
          redirectUri: http://localhost:8080/login/oauth2/code/kakao
          scope:
            - profile_nickname
            - profile_image
            - account_email
          clientName: Kakao
      # Provider 설정
      provider:
        naver:
          authorization-uri: https://nid.naver.com/oauth2.0/authorize
          token-uri: https://nid.naver.com/oauth2.0/token
          user-info-uri: https://openapi.naver.com/v1/nid/me
          user-name-attribute: response # 회원정보를 json의 response 키값으로 리턴해줌.
        kakao:
          authorizationUri: https://kauth.kakao.com/oauth/authorize
          tokenUri: https://kauth.kakao.com/oauth/token
          userInfoUri: https://kapi.kakao.com/v2/user/me
          userNameAttribute: id